
development:
  api_key: 6f4c403911285aa163175607730290ac
  secret_key: dfcaa89388d664fee714acb3be60d621
  canvas_page_name: iiframeone
  callback_url: http://bikle.net:3331/
  pretty_errors: true
  set_asset_host_to_callback_url: true

cucumber:
  api_key: 6f4c403911285aa163175607730290ac
  secret_key: dfcaa89388d664fee714acb3be60d621
  canvas_page_name: iiframeone
  callback_url: http://bikle.net:3331/
  pretty_errors: true
  set_asset_host_to_callback_url: true

test:
  api_key: 6f4c403911285aa163175607730290ac
  secret_key: dfcaa89388d664fee714acb3be60d621
  canvas_page_name: iiframeone
  callback_url: http://bikle.net:3331/
  pretty_errors: true
  set_asset_host_to_callback_url: true

production:
  api_key: 3756b8c191faac9ac44082fd2cac997b
  secret_key: 79d64b0a8fb94f0e528a74e91e9f51eb
  canvas_page_name: ffbiframe
  callback_url: http://ffbiframe.heroku.com/
  pretty_errors: true
  set_asset_host_to_callback_url: true
